#!/usr/bin/env python3

import json
import os
import sys

def generate_pr_comment():
    try:
        with open('coverage_analysis.json', 'r') as f:
            analysis = json.load(f)
        
        suggestions = analysis.get('suggestions', [])
        total_coverage = analysis.get('total_coverage', 0)
        threshold = analysis.get('threshold', 80)
        files_needing_tests = analysis.get('files_needing_tests', 0)
        
        if not suggestions:
            return None
        
        comment = "## 🧪 Test Coverage Analysis\n\n"
        comment += f"**Overall Coverage**: {total_coverage:.1f}% (threshold: {threshold}%)\n"
        comment += f"**Files needing tests**: {files_needing_tests}\n\n"
        
        top_suggestions = suggestions[:3]
        
        for i, suggestion in enumerate(top_suggestions, 1):
            comment += f"### {i}. `{suggestion['file']}` ({suggestion['coverage']:.1f}% coverage)\n"
            comment += f"**Functions**: {suggestion['analysis']['functions']} | **Classes**: {suggestion['analysis']['classes']} | **Lines**: {suggestion['analysis']['lines']}\n\n"
            comment += f"**Suggested test file**: `{suggestion['test_filename']}`\n\n"
            comment += "```python\n" + suggestion['test_code'] + "\n```\n\n"
        
        if len(suggestions) > 3:
            comment += f"<details><summary>Show {len(suggestions) - 3} more files needing tests</summary>\n\n"
            for suggestion in suggestions[3:]:
                comment += f"- `{suggestion['file']}` ({suggestion['coverage']:.1f}% coverage) - {suggestion['analysis']['functions']} functions, {suggestion['analysis']['classes']} classes\n"
            comment += "\n</details>\n"
        
        comment += "\n---\n*Generated by Python Test Coverage Analyzer*"
        
        return comment
        
    except Exception as e:
        print(f"Error generating PR comment: {e}", file=sys.stderr)
        return None

def main():
    comment = generate_pr_comment()
    
    if comment:
        with open('pr_comment.md', 'w') as f:
            f.write(comment)
        print("PR comment generated successfully")
    else:
        print("No PR comment needed")

if __name__ == '__main__':
    main()